const pokemon = [
  { id: 1, name: "Bulbasaur", types: ["Grass", "Poison"], description: "A strange seed was planted on its back at birth. The plant sprouts and grows with this Pokémon." },
  { id: 2, name: "Ivysaur", types: ["Grass", "Poison"], description: "When the bulb on its back grows large, it appears to lose the ability to stand on its hind legs." },
  { id: 3, name: "Venusaur", types: ["Grass", "Poison"], description: "The plant blooms when it is absorbing solar energy. It stays on the move to seek sunlight." },
  { id: 4, name: "Charmander", types: ["Fire"], description: "Obviously prefers hot places. When it rains, steam is said to spout from the tip of its tail." },
  { id: 5, name: "Charmeleon", types: ["Fire"], description: "When it swings its burning tail, it elevates the temperature to unbearably high levels." },
  { id: 6, name: "Charizard", types: ["Fire", "Flying"], description: "Spits fire that is hot enough to melt boulders. Known to cause forest fires unintentionally." },
  { id: 7, name: "Squirtle", types: ["Water"], description: "After birth, its back swells and hardens into a shell. Powerfully sprays foam from its mouth." },
  { id: 8, name: "Wartortle", types: ["Water"], description: "Often hides in water to stalk unwary prey. For swimming fast, it moves its ears to maintain balance." },
  { id: 9, name: "Blastoise", types: ["Water"], description: "A brutal Pokémon with pressurized water jets on its shell. They are used for high speed tackles." },
  { id: 10, name: "Caterpie", types: ["Bug"], description: "Its short feet are tipped with suction pads that enable it to tirelessly climb slopes and walls." },
  { id: 11, name: "Metapod", types: ["Bug"], description: "This Pokémon is vulnerable to attack while its shell is soft, exposing its weak and tender body." },
  { id: 12, name: "Butterfree", types: ["Bug", "Flying"], description: "In battle, it flaps its wings at high speed to release highly toxic dust into the air." },
  { id: 13, name: "Weedle", types: ["Bug", "Poison"], description: "Often found in forests, eating leaves. It has a sharp venomous stinger on its head." },
  { id: 14, name: "Kakuna", types: ["Bug", "Poison"], description: "Almost incapable of moving, this Pokémon can only harden its shell to protect itself from predators." },
  { id: 15, name: "Beedrill", types: ["Bug", "Poison"], description: "Flies at high speed and attacks using its large venomous stingers on its forelegs and tail." },
  { id: 16, name: "Pidgey", types: ["Normal", "Flying"], description: "A common sight in forests and woods. It flaps its wings at ground level to kick up blinding sand." },
  { id: 17, name: "Pidgeotto", types: ["Normal", "Flying"], description: "Very protective of its sprawling territorial area, this Pokémon will fiercely peck at any intruder." },
  { id: 18, name: "Pidgeot", types: ["Normal", "Flying"], description: "When hunting, it skims the surface of water at high speed to pick off unwary prey such as Magikarp." },
  { id: 19, name: "Rattata", types: ["Normal"], description: "Bites anything when it attacks. Small and very quick, it is a common sight in many places." },
  { id: 20, name: "Raticate", types: ["Normal"], description: "It uses its whiskers to maintain its balance. It apparently slows down if they are cut off." },
  { id: 21, name: "Spearow", types: ["Normal", "Flying"], description: "Eats bugs in grassy areas. It has to flap its short wings at high speed to stay airborne." },
  { id: 22, name: "Fearow", types: ["Normal", "Flying"], description: "With its huge and magnificent wings, it can keep aloft without ever having to land for rest." },
  { id: 23, name: "Ekans", types: ["Poison"], description: "Moves silently and stealthily. Eats the eggs of birds, such as Pidgey and Spearow, whole." },
  { id: 24, name: "Arbok", types: ["Poison"], description: "It is rumored that the ferocious warning markings on its belly differ from area to area." },
  { id: 25, name: "Pikachu", types: ["Electric"], description: "When several of these Pokémon gather, their electricity could build and cause lightning storms." },
  { id: 26, name: "Raichu", types: ["Electric"], description: "Its long tail serves as a ground to protect itself from its own high voltage power." },
  { id: 27, name: "Sandshrew", types: ["Ground"], description: "Burrows deep underground in arid locations far from water. It only emerges to hunt for food." },
  { id: 28, name: "Sandslash", types: ["Ground"], description: "Curls up into a spiny ball when threatened. It can roll while curled up to attack or escape." },
  { id: 29, name: "Nidoran♀", types: ["Poison"], description: "Although small, its venomous barbs render this Pokémon dangerous. The female has smaller horns." },
  { id: 30, name: "Nidorina", types: ["Poison"], description: "The female's horn develops slowly. Prefers physical attacks such as clawing and biting." },
  { id: 31, name: "Nidoqueen", types: ["Poison", "Ground"], description: "Its hard scales provide strong protection. It uses its hefty bulk to execute powerful moves." },
  { id: 32, name: "Nidoran♂", types: ["Poison"], description: "Stiffens its ears to sense danger. The larger its horns, the more powerful its secreted venom." },
  { id: 33, name: "Nidorino", types: ["Poison"], description: "An aggressive Pokémon that is quick to attack. The horn on its head secretes a powerful venom." },
  { id: 34, name: "Nidoking", types: ["Poison", "Ground"], description: "It uses its powerful tail in battle to smash, constrict, then break the prey's bones." },
  { id: 35, name: "Clefairy", types: ["Fairy"], description: "Its magical and cute appeal has many admirers. It is rare and found only in certain areas." },
  { id: 36, name: "Clefable", types: ["Fairy"], description: "A timid fairy Pokémon that is rarely seen. It will run and hide the moment it senses people." },
  { id: 37, name: "Vulpix", types: ["Fire"], description: "At the time of birth, it has just one tail. The tail splits from its tip as it grows older." },
  { id: 38, name: "Ninetales", types: ["Fire"], description: "Very smart and very vengeful. Grabbing one of its many tails could result in a 1000-year curse." },
  { id: 39, name: "Jigglypuff", types: ["Normal", "Fairy"], description: "When its huge eyes light up, it sings a mysteriously soothing melody that lulls its enemies to sleep." },
  { id: 40, name: "Wigglytuff", types: ["Normal", "Fairy"], description: "The body is soft and rubbery. When angered, it will suck in air and inflate itself to an enormous size." },
  { id: 41, name: "Zubat", types: ["Poison", "Flying"], description: "Forms colonies in perpetually dark places. Uses ultrasonic waves to identify and approach targets." },
  { id: 42, name: "Golbat", types: ["Poison", "Flying"], description: "Once it strikes, it will not stop draining energy from the victim even if it gets too heavy to fly." },
  { id: 43, name: "Oddish", types: ["Grass", "Poison"], description: "During the day, it keeps its face buried in the ground. At night, it wanders around sowing its seeds." },
  { id: 44, name: "Gloom", types: ["Grass", "Poison"], description: "The fluid that oozes from its mouth isn't drool. It is a nectar that is used to attract prey." },
  { id: 45, name: "Vileplume", types: ["Grass", "Poison"], description: "The larger its petals, the more toxic pollen it contains. Its big head is heavy and hard to hold up." },
  { id: 46, name: "Paras", types: ["Bug", "Grass"], description: "Burrows to suck tree roots. The mushrooms on its back grow by drawing nutrients from the bug host." },
  { id: 47, name: "Parasect", types: ["Bug", "Grass"], description: "A host-parasite pair in which the parasite mushroom has taken over the host bug. Prefers damp places." },
  { id: 48, name: "Venonat", types: ["Bug", "Poison"], description: "Lives in the shadows of tall trees where it eats insects. It is attracted by light at night." },
  { id: 49, name: "Venomoth", types: ["Bug", "Poison"], description: "The dust-like scales covering its wings are color coded to indicate the kinds of poison it has." },
  { id: 50, name: "Diglett", types: ["Ground"], description: "Lives about one yard underground where it feeds on plant roots. It sometimes appears above ground." },
  { id: 51, name: "Dugtrio", types: ["Ground"], description: "A team of Diglett triplets. It triggers huge earthquakes by burrowing 60 miles underground." },
  { id: 52, name: "Meowth", types: ["Normal"], description: "Adores circular objects. Wanders the streets on a nightly basis to look for dropped loose change." },
  { id: 53, name: "Persian", types: ["Normal"], description: "Although its fur has many admirers, it is tough to raise as a pet because of its fickle meanness." },
  { id: 54, name: "Psyduck", types: ["Water"], description: "While lulling its enemies with its vacant look, this wily Pokémon will use psychokinetic powers." },
  { id: 55, name: "Golduck", types: ["Water"], description: "Often seen swimming elegantly by lake shores. It is often mistaken for the Japanese monster, Kappa." },
  { id: 56, name: "Mankey", types: ["Fighting"], description: "Extremely quick to anger. It could be docile one moment then thrashing away the next instant." },
  { id: 57, name: "Primeape", types: ["Fighting"], description: "Always furious and tenacious to boot. It will not abandon chasing its quarry until it is caught." },
  { id: 58, name: "Growlithe", types: ["Fire"], description: "Very protective of its territory. It will bark and bite to repel intruders from its space." },
  { id: 59, name: "Arcanine", types: ["Fire"], description: "A Pokémon that has been admired since the past for its beauty. It runs agilely as if on wings." },
  { id: 60, name: "Poliwag", types: ["Water"], description: "Its newly grown legs prevent it from running. It appears to prefer swimming than trying to stand." },
  { id: 61, name: "Poliwhirl", types: ["Water"], description: "Capable of living in or out of water. When out of water, it sweats to keep its body slimy." },
  { id: 62, name: "Poliwrath", types: ["Water", "Fighting"], description: "An adept swimmer at both the front crawl and breast stroke. Easily overtakes the best human swimmers." },
  { id: 63, name: "Abra", types: ["Psychic"], description: "Using its ability to read minds, it will identify impending danger and teleport to safety." },
  { id: 64, name: "Kadabra", types: ["Psychic"], description: "It emits special alpha waves from its body that induce headaches just by being close by." },
  { id: 65, name: "Alakazam", types: ["Psychic"], description: "Its brain can outperform a supercomputer. Its intelligence quotient is said to be 5,000." },
  { id: 66, name: "Machop", types: ["Fighting"], description: "Loves to build its muscles. It trains in all styles of martial arts to become even stronger." },
  { id: 67, name: "Machoke", types: ["Fighting"], description: "Its muscular body is so powerful, it must wear a power save belt to be able to regulate its motions." },
  { id: 68, name: "Machamp", types: ["Fighting"], description: "Using its heavy muscles, it throws powerful punches that can send the victim clear over the horizon." },
  { id: 69, name: "Bellsprout", types: ["Grass", "Poison"], description: "A carnivorous Pokémon that traps and eats bugs. It uses its root feet to soak up needed moisture." },
  { id: 70, name: "Weepinbell", types: ["Grass", "Poison"], description: "It spits out poisonpowder to immobilize the enemy and then finishes it with a spray of acid." },
  { id: 71, name: "Victreebel", types: ["Grass", "Poison"], description: "Said to live in huge colonies deep in jungles, although no one has ever returned from there." },
  { id: 72, name: "Tentacool", types: ["Water", "Poison"], description: "Drifts in shallow seas. Anglers who hook them by accident are often punished by its stinging acid." },
  { id: 73, name: "Tentacruel", types: ["Water", "Poison"], description: "The tentacles are normally kept short. On hunts, they are extended to ensnare and immobilize prey." },
  { id: 74, name: "Geodude", types: ["Rock", "Ground"], description: "Found in fields and mountains. Mistaking them for boulders, people often step or trip on them." },
  { id: 75, name: "Graveler", types: ["Rock", "Ground"], description: "Rolls down slopes to move. It rolls over any obstacle without slowing or changing its direction." },
  { id: 76, name: "Golem", types: ["Rock", "Ground"], description: "Its boulder-like body is extremely hard. It can easily withstand dynamite blasts without damage." },
  { id: 77, name: "Ponyta", types: ["Fire"], description: "Its hooves are 10 times harder than diamonds. It can trample anything completely flat in little time." },
  { id: 78, name: "Rapidash", types: ["Fire"], description: "Very competitive, this Pokémon will chase anything that moves fast in the hopes of racing it." },
  { id: 79, name: "Slowpoke", types: ["Water", "Psychic"], description: "Incredibly slow and dopey. It takes 5 seconds for it to feel pain when under attack." },
  { id: 80, name: "Slowbro", types: ["Water", "Psychic"], description: "The Shellder that is latched onto Slowpoke's tail is said to feed on the host's left over scraps." },
  { id: 81, name: "Magnemite", types: ["Electric", "Steel"], description: "Uses anti-gravity to stay suspended. Appears without warning and uses Thunder Wave and similar moves." },
  { id: 82, name: "Magneton", types: ["Electric", "Steel"], description: "Formed by several Magnemites linked together. They frequently appear when sunspots flare up." },
  { id: 83, name: "Farfetch'd", types: ["Normal", "Flying"], description: "The sprig of green onions it holds is its weapon. It is used much like a metal sword." },
  { id: 84, name: "Doduo", types: ["Normal", "Flying"], description: "A bird that makes up for its poor flying with its fast foot speed. Leaves giant footprints." },
  { id: 85, name: "Dodrio", types: ["Normal", "Flying"], description: "Uses its three brains to execute complex plans. While two heads sleep, one head stays awake." },
  { id: 86, name: "Seel", types: ["Water"], description: "The protruding horn on its head is very hard. It is used for bashing through thick ice." },
  { id: 87, name: "Dewgong", types: ["Water", "Ice"], description: "Stores thermal energy in its body. Swims at a steady 8 knots even in intensely cold waters." },
  { id: 88, name: "Grimer", types: ["Poison"], description: "Appears in filthy areas. Thrives by sucking up polluted sludge that is pumped out of factories." },
  { id: 89, name: "Muk", types: ["Poison"], description: "Thickly covered with a filthy, vile sludge. It is so toxic, even its footprints contain poison." },
  { id: 90, name: "Shellder", types: ["Water"], description: "Its hard shell repels any kind of attack. It is vulnerable only when its shell is open." },
  { id: 91, name: "Cloyster", types: ["Water", "Ice"], description: "When attacked, it launches its horns in quick volleys. Its innards have never been seen." },
  { id: 92, name: "Gastly", types: ["Ghost", "Poison"], description: "Almost invisible, this gaseous Pokémon cloaks the target and puts it to sleep without notice." },
  { id: 93, name: "Haunter", types: ["Ghost", "Poison"], description: "Because of its ability to slip through block walls, it is said to be from another dimension." },
  { id: 94, name: "Gengar", types: ["Ghost", "Poison"], description: "Under a full moon, this Pokémon likes to mimic the shadows of people and laugh at their fright." },
  { id: 95, name: "Onix", types: ["Rock", "Ground"], description: "As it grows, the stone portions of its body harden to become similar to a diamond, but colored black." },
  { id: 96, name: "Drowzee", types: ["Psychic"], description: "Puts enemies to sleep then eats their dreams. Occasionally gets sick from eating bad dreams." },
  { id: 97, name: "Hypno", types: ["Psychic"], description: "When it locks eyes with an enemy, it will use a mix of psi moves such as hypnosis and confusion." },
  { id: 98, name: "Krabby", types: ["Water"], description: "Its pincers are not only powerful weapons, they are used for balance when walking sideways." },
  { id: 99, name: "Kingler", types: ["Water"], description: "The large pincer has 10000 hp of crushing power. However, its huge size makes it unwieldy to use." },
  { id: 100, name: "Voltorb", types: ["Electric"], description: "Usually found in power plants. Easily mistaken for a Poké Ball, they have zapped many people." },
  { id: 101, name: "Electrode", types: ["Electric"], description: "It stores electric energy under very high pressure. It often explodes with little or no provocation." },
  { id: 102, name: "Exeggcute", types: ["Grass", "Psychic"], description: "Often mistaken for eggs. When disturbed, they quickly gather and attack in swarms." },
  { id: 103, name: "Exeggutor", types: ["Grass", "Psychic"], description: "Legend has it that on rare occasions, one of its heads will drop off and continue on as an Exeggcute." },
  { id: 104, name: "Cubone", types: ["Ground"], description: "Because it never removes its skull helmet, no one has ever seen this Pokémon's real face." },
  { id: 105, name: "Marowak", types: ["Ground"], description: "The bone it holds is its key weapon. It throws the bone skillfully like a boomerang to KO targets." },
  { id: 106, name: "Hitmonlee", types: ["Fighting"], description: "When in a hurry, its legs lengthen progressively. It runs smoothly with extra long, loping strides." },
  { id: 107, name: "Hitmonchan", types: ["Fighting"], description: "While apparently doing nothing, it fires punches in lightning fast volleys that are impossible to see." },
  { id: 108, name: "Lickitung", types: ["Normal"], description: "Its tongue can be extended like a chameleon's. It leaves a tingling sensation when it licks enemies." },
  { id: 109, name: "Koffing", types: ["Poison"], description: "Because it stores several kinds of toxic gases in its body, it is prone to exploding without warning." },
  { id: 110, name: "Weezing", types: ["Poison"], description: "Where two kinds of poison gases meet, 2 Koffings can fuse into a Weezing over many years." },
  { id: 111, name: "Rhyhorn", types: ["Ground", "Rock"], description: "Its massive bones are 1000 times harder than human bones. It can easily knock a trailer flying." },
  { id: 112, name: "Rhydon", types: ["Ground", "Rock"], description: "Protected by an armor-like hide, it is capable of living in molten lava of 3,600 degrees." },
  { id: 113, name: "Chansey", types: ["Normal"], description: "A rare and elusive Pokémon that is said to bring happiness to those who manage to get it." },
  { id: 114, name: "Tangela", types: ["Grass"], description: "The whole body is swathed with wide vines that are similar to seaweed. Its vines shake as it walks." },
  { id: 115, name: "Kangaskhan", types: ["Normal"], description: "The infant rarely ventures out of its mother's protective pouch until it is 3 years old." },
  { id: 116, name: "Horsea", types: ["Water"], description: "Known to shoot down flying bugs with precision blasts of ink from the surface of the water." },
  { id: 117, name: "Seadra", types: ["Water"], description: "Capable of swimming backwards by rapidly flapping its wing-like pectoral fins and stout tail." },
  { id: 118, name: "Goldeen", types: ["Water"], description: "Its tail fin billows like an elegant ballroom dress, giving it the nickname of the Water Queen." },
  { id: 119, name: "Seaking", types: ["Water"], description: "In the autumn spawning season, they can be seen swimming powerfully up rivers and creeks." },
  { id: 120, name: "Staryu", types: ["Water"], description: "An enigmatic Pokémon that can effortlessly regenerate any appendage it loses in battle." },
  { id: 121, name: "Starmie", types: ["Water", "Psychic"], description: "Its central core glows with the seven colors of the rainbow. Some people value the core as a gem." },
  { id: 122, name: "Mr. Mime", types: ["Psychic", "Fairy"], description: "If interrupted while it is miming, it will slap around the offender with its broad hands." },
  { id: 123, name: "Scyther", types: ["Bug", "Flying"], description: "With ninja-like agility and speed, it can create the illusion that there is more than one." },
  { id: 124, name: "Jynx", types: ["Ice", "Psychic"], description: "It seductively wiggles its hips as it walks. It can cause people to dance in unison with it." },
  { id: 125, name: "Electabuzz", types: ["Electric"], description: "Normally found near power plants, they can wander away and cause major blackouts in cities." },
  { id: 126, name: "Magmar", types: ["Fire"], description: "Its body always burns with an orange glow that enables it to hide perfectly among flames." },
  { id: 127, name: "Pinsir", types: ["Bug"], description: "If it fails to crush the victim in its pincers, it will swing it around and toss it hard." },
  { id: 128, name: "Tauros", types: ["Normal"], description: "When it targets an enemy, it charges furiously while whipping its body with its long tails." },
  { id: 129, name: "Magikarp", types: ["Water"], description: "In the distant past, it was somewhat stronger than the horribly weak descendants that exist today." },
  { id: 130, name: "Gyarados", types: ["Water", "Flying"], description: "Rarely seen in the wild. Huge and vicious, it is capable of destroying entire cities in a rage." },
  { id: 131, name: "Lapras", types: ["Water", "Ice"], description: "A Pokémon that has been overhunted almost to extinction. It can ferry people across the sea." },
  { id: 132, name: "Ditto", types: ["Normal"], description: "Capable of copying an enemy's genetic code to instantly transform itself into a duplicate of the enemy." },
  { id: 133, name: "Eevee", types: ["Normal"], description: "Its genetic code is irregular. It may mutate if it is exposed to radiation from element stones." },
  { id: 134, name: "Vaporeon", types: ["Water"], description: "Lives close to water. Its long tail is ridged with a fin which is often mistaken for a mermaid's." },
  { id: 135, name: "Jolteon", types: ["Electric"], description: "It accumulates negative ions in the atmosphere to blast out 10000-volt lightning bolts." },
  { id: 136, name: "Flareon", types: ["Fire"], description: "When storing thermal energy in its body, its temperature could soar to over 1600 degrees." },
  { id: 137, name: "Porygon", types: ["Normal"], description: "A Pokémon that consists entirely of programming code. Capable of moving freely in cyberspace." },
  { id: 138, name: "Omanyte", types: ["Rock", "Water"], description: "Although long extinct, in rare cases, it can be genetically resurrected from fossils." },
  { id: 139, name: "Omastar", types: ["Rock", "Water"], description: "A prehistoric Pokémon that died out when its heavy shell made it impossible to catch prey." },
  { id: 140, name: "Kabuto", types: ["Rock", "Water"], description: "A Pokémon that was resurrected from a fossil found in what was once the ocean floor eons ago." },
  { id: 141, name: "Kabutops", types: ["Rock", "Water"], description: "Its sleek shape is perfect for swimming. It slashes prey with its claws and drains the body fluids." },
  { id: 142, name: "Aerodactyl", types: ["Rock", "Flying"], description: "A ferocious, prehistoric Pokémon that goes for the enemy's throat with its serrated saw-like fangs." },
  { id: 143, name: "Snorlax", types: ["Normal"], description: "Very lazy. Just eats and sleeps. As its rotund bulk builds, it becomes steadily more slothful." },
  { id: 144, name: "Articuno", types: ["Ice", "Flying"], description: "A legendary bird Pokémon that is said to appear to doomed people who are lost in icy mountains." },
  { id: 145, name: "Zapdos", types: ["Electric", "Flying"], description: "A legendary bird Pokémon that is said to appear from clouds while dropping enormous lightning bolts." },
  { id: 146, name: "Moltres", types: ["Fire", "Flying"], description: "Known as the legendary bird of fire. Every flap of its wings creates a dazzling flash of flames." },
  { id: 147, name: "Dratini", types: ["Dragon"], description: "Long considered a mythical Pokémon until recently when a small colony was found living underwater." },
  { id: 148, name: "Dragonair", types: ["Dragon"], description: "A mystical Pokémon that exudes a gentle aura. Has the ability to change climate conditions." },
  { id: 149, name: "Dragonite", types: ["Dragon", "Flying"], description: "An extremely rarely seen marine Pokémon. Its intelligence is said to match that of humans." },
  { id: 150, name: "Mewtwo", types: ["Psychic"], description: "It was created by a scientist after years of horrific gene splicing and DNA engineering experiments." },
  { id: 151, name: "Mew", types: ["Psychic"], description: "So rare that it is still said to be a mirage by many experts. Only a few people have seen it worldwide." }
];

module.exports = pokemon;